// Automatically generated by flapigen
package club.gamza.warpsquare.engine;


public enum Color {
    White(0),
    Black(1);

    private final int value;
    Color(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static Color fromInt(int x) {
        switch (x) {
            case 0: return White;
            case 1: return Black;
            default: throw new Error("Invalid value for enum Color: " + x);
        }
    }
}
