// Automatically generated by flapigen
package club.gamza.warpsquare.engine;


public enum File {
    Z(0),
    A(1),
    B(2),
    C(3),
    D(4),
    E(5);

    private final int value;
    File(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static File fromInt(int x) {
        switch (x) {
            case 0: return Z;
            case 1: return A;
            case 2: return B;
            case 3: return C;
            case 4: return D;
            case 5: return E;
            default: throw new Error("Invalid value for enum File: " + x);
        }
    }
}
