// Automatically generated by flapigen
package club.gamza.warpsquare.engine;


public enum Level {
    White(0),
    Neutral(1),
    Black(2),
    QL1(3),
    QL2(4),
    QL3(5),
    QL4(6),
    QL5(7),
    QL6(8),
    KL1(9),
    KL2(10),
    KL3(11),
    KL4(12),
    KL5(13),
    KL6(14);

    private final int value;
    Level(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static Level fromInt(int x) {
        switch (x) {
            case 0: return White;
            case 1: return Neutral;
            case 2: return Black;
            case 3: return QL1;
            case 4: return QL2;
            case 5: return QL3;
            case 6: return QL4;
            case 7: return QL5;
            case 8: return QL6;
            case 9: return KL1;
            case 10: return KL2;
            case 11: return KL3;
            case 12: return KL4;
            case 13: return KL5;
            case 14: return KL6;
            default: throw new Error("Invalid value for enum Level: " + x);
        }
    }
}
