// Automatically generated by flapigen
package club.gamza.warpsquare.engine;


public enum PieceType {
    Pawn(0),
    Knight(1),
    Bishop(2),
    Rook(3),
    Queen(4),
    King(5);

    private final int value;
    PieceType(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static PieceType fromInt(int x) {
        switch (x) {
            case 0: return Pawn;
            case 1: return Knight;
            case 2: return Bishop;
            case 3: return Rook;
            case 4: return Queen;
            case 5: return King;
            default: throw new Error("Invalid value for enum PieceType: " + x);
        }
    }
}
