// Automatically generated by flapigen
package club.gamza.warpsquare.engine;


public enum Rank {
    Zero(0),
    One(1),
    Two(2),
    Three(3),
    Four(4),
    Five(5),
    Six(6),
    Seven(7),
    Eight(8),
    Nine(9);

    private final int value;
    Rank(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static Rank fromInt(int x) {
        switch (x) {
            case 0: return Zero;
            case 1: return One;
            case 2: return Two;
            case 3: return Three;
            case 4: return Four;
            case 5: return Five;
            case 6: return Six;
            case 7: return Seven;
            case 8: return Eight;
            case 9: return Nine;
            default: throw new Error("Invalid value for enum Rank: " + x);
        }
    }
}
