on: push

jobs:
  build:
    name: Build ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo Build
        working-directory: ./java
        run: cargo build --release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-${{ matrix.os }}
          path: ./target/release
