on: push

jobs:
  release:
    name: Release Windows
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          working-directory: ./java
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-windows
          path: ./target/release/engine_java.dll

        # uses: rust-build/rust-build.action@v1.4.4
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
